[package]
name = "rustcg"
version = "0.1.0"
authors = ["WeAthFolD <weathfold@li-dev.cn>"]
#build = "build.rs"

[dependencies]
glutin = "0.19"
gfx = "0.17.1"
gfx_core = "0.8"
gfx_device_gl = "0.15"
gfx_window_glutin = "0.28.0"
cgmath = "0.16.1"